# Generated by Django 3.0.7 on 2020-06-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[(0, 'Sendo criado'), (1, 'Em espera'), (2, 'Em produção'), (3, 'Cancelado'), (4, 'Saiu para entrega'), (5, 'Finalizado')], max_length=20),
        ),
    ]
