# Generated by Django 3.0.7 on 2020-06-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20200629_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Sendo criado'), (1, 'Em espera'), (2, 'Em produção'), (3, 'Cancelado'), (4, 'Saiu para entrega'), (5, 'Finalizado')]),
        ),
    ]
